flowchart LR

    REST_IN([fa:fa-circle-right POST Request \n transponderId, gate, lot ])

    AMQP_IN([fa:fa-circle-right AMQP fa:fa-envelope\n permit.validated.response.queue])
    AMQP_OUT([fa:fa-envelope AMQP fa:fa-circle-right\n permit.validated.request.queue])


    subgraph "<< gate-access-service >>"
        REQUEST_IN("<< InputPort >>\n RequestReceiver")
        RESPONSE_IN("<< InputPort >>\n ResponseReceiver")
        SERVICE{{"\nGateAccess\nService\n<br>"}}
        HRM_SENDER("<< OutputPort >>\n RequestSender")
    end

    REST_IN -- TransponderAccessRequest--> REQUEST_IN
    AMQP_IN -- AccessResult --> RESPONSE_IN
    REQUEST_IN -. offered .- SERVICE
    RESPONSE_IN -. offered .- SERVICE


SERVICE -. required .- HRM_SENDER
HRM_SENDER -- TransponderAccessRequest --> AMQP_OUT
