include:
  # Loading the technical infrastructure
  - ./../infrastructure/docker-compose.yml

services:

  access-control-service:
    container_name: access-control-service
    build:
      context: ../services/access-control-service
    ports:
      - "8081:8081"
    depends_on:
      rabbitmq:
        condition: service_healthy
      service-registry:
        condition: service_healthy

  permit-service:
    container_name: permit-service
    build:
      context: ../services/permit-service
    ports:
      - "8082:8082"
    depends_on:
      rabbitmq:
        condition: service_healthy
      service-registry:
        condition: service_healthy
