include:
  # Loading the message broker standalone deployment
  - ./message-broker/docker-compose.yml

services:

  service-registry:
    container_name: service-registry
    build:
      context: ./service-registry
    ports:
      - "8761:8761"
    healthcheck:
      test: curl -f http://localhost:8761
      start_period: 3s
      interval: 1s
      timeout: 1s
      retries: 10